# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

volumes:
  mysql-volume:

services:
  database:
    image: mysql:8.0.22
    ports:
      - "3306:3306"
    #Specify where the persisted Data should be stored
    volumes:
      - mysql-volume:/var/lib/mysql
    environment: 
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: FuStudy

  fustudy_api:
    build:
      context: .
      dockerfile: FuStudy_API/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
  redis:
    image: redis:alpine